AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/*_helper.rb'
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 128
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
