AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'spec/*_helper.rb'
    - 'vendor/**/*'
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
