AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 128
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
